### ISSUE TITLE
你好，你是如何用python在ROS中生成自定义地图的？

### ISSUE THREAD

**Issue by PiBigStar5712** [Friedrich-M/Robot#1]
如题，我看到你项目说明中的gazebo仿真图片显示的是你的自定义地图。但我在你的项目代码中没有看到ROS下的地图生成的相关代码。所以想请教你一下如何使用python编写一个ROS下的自定义地图并发布到rviz或者gazebo中，以及如何将机器人坐标映射到地图中。

**Comment by Friedrich-M** [comment]
可以参考最新上传的gazebo建图和tf发布的代码
